# Generated by Django 5.2.8 on 2025-11-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_mail', models.CharField(max_length=100)),
                ('reg_password', models.CharField(max_length=100)),
            ],
        ),
    ]
