# Generated by Django 5.2.8 on 2025-11-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='reg_mail',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
